// <auto-generated />
using System;
using LinkHub.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LinkHub.Infrastructure.Migrations
{
    [DbContext(typeof(LinkHubDbContext))]
    [Migration("20260214161500_UpdateContactSchema")]
    partial class UpdateContactSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClientContact", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ClientId", "ContactId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ContactId");

                    b.ToTable("ClientContacts");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            ContactId = 1,
                            LinkedAt = new DateTime(2026, 2, 14, 16, 14, 59, 917, DateTimeKind.Utc).AddTicks(7107)
                        },
                        new
                        {
                            ClientId = 1,
                            ContactId = 2,
                            LinkedAt = new DateTime(2026, 2, 14, 16, 14, 59, 917, DateTimeKind.Utc).AddTicks(7109)
                        },
                        new
                        {
                            ClientId = 2,
                            ContactId = 1,
                            LinkedAt = new DateTime(2026, 2, 14, 16, 14, 59, 917, DateTimeKind.Utc).AddTicks(7110)
                        });
                });

            modelBuilder.Entity("ClientContact1", b =>
                {
                    b.Property<int>("ClientsId")
                        .HasColumnType("int");

                    b.Property<int>("ContactsId")
                        .HasColumnType("int");

                    b.HasKey("ClientsId", "ContactsId");

                    b.HasIndex("ContactsId");

                    b.ToTable("ClientContact1");
                });

            modelBuilder.Entity("LinkHub.Domain.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NoOfLinkedContacts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientCode")
                        .IsUnique();

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientCode = "UDE001",
                            CreatedAt = new DateTime(2026, 2, 14, 16, 14, 59, 917, DateTimeKind.Utc).AddTicks(7088),
                            Name = "Udemy",
                            NoOfLinkedContacts = 0,
                            UpdatedAt = new DateTime(2026, 2, 14, 16, 14, 59, 917, DateTimeKind.Utc).AddTicks(7093)
                        },
                        new
                        {
                            Id = 2,
                            ClientCode = "WTC002",
                            CreatedAt = new DateTime(2026, 2, 14, 16, 14, 59, 917, DateTimeKind.Utc).AddTicks(7096),
                            Name = "weThinkCode",
                            NoOfLinkedContacts = 0,
                            UpdatedAt = new DateTime(2026, 2, 14, 16, 14, 59, 917, DateTimeKind.Utc).AddTicks(7096)
                        });
                });

            modelBuilder.Entity("LinkHub.Domain.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NoOfLinkedClients")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 14, 59, 917, DateTimeKind.Utc).AddTicks(7101),
                            Email = "dev@example.com",
                            Name = "DEV",
                            NoOfLinkedClients = 0,
                            Surname = "Team",
                            UpdatedAt = new DateTime(2026, 2, 14, 16, 14, 59, 917, DateTimeKind.Utc).AddTicks(7102)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 14, 16, 14, 59, 917, DateTimeKind.Utc).AddTicks(7105),
                            Email = "qa@example.com",
                            Name = "QA",
                            NoOfLinkedClients = 0,
                            Surname = "Team",
                            UpdatedAt = new DateTime(2026, 2, 14, 16, 14, 59, 917, DateTimeKind.Utc).AddTicks(7105)
                        });
                });

            modelBuilder.Entity("ClientContact", b =>
                {
                    b.HasOne("LinkHub.Domain.Models.Client", "Client")
                        .WithMany("ClientContacts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkHub.Domain.Models.Contact", "Contact")
                        .WithMany("ClientContacts")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("ClientContact1", b =>
                {
                    b.HasOne("LinkHub.Domain.Models.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LinkHub.Domain.Models.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LinkHub.Domain.Models.Client", b =>
                {
                    b.Navigation("ClientContacts");
                });

            modelBuilder.Entity("LinkHub.Domain.Models.Contact", b =>
                {
                    b.Navigation("ClientContacts");
                });
#pragma warning restore 612, 618
        }
    }
}
